"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { deflateRawSync } = require("node:zlib");
const zip = require("../office-zip");

const endOffset = (buffer) => buffer.length - 22;
const centralOffset = (buffer) => buffer.readUInt32LE(endOffset(buffer) + 16);
function checksum(data) {
  let crc = 0xffffffff;
  for (const value of data) {
    crc ^= value;
    for (let bit = 0; bit < 8; bit++) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
  }
  return (crc ^ 0xffffffff) >>> 0;
}

// Independent one-entry writer for archives our exporter does not produce,
// including stream descriptors, hostile names, and forged size declarations.
function fixture(name, data = Buffer.from("payload"), options = {}) {
  const nameBytes = Buffer.isBuffer(name) ? name : Buffer.from(name);
  const method = options.method ?? 8;
  const packed = options.packed || (method === 8 ? deflateRawSync(data) : data);
  const flags = options.flags ?? (0x800 | (options.descriptor ? 8 : 0));
  const size = options.size ?? data.length, crc = checksum(data);
  const local = Buffer.alloc(30), central = Buffer.alloc(46), end = Buffer.alloc(22);
  local.writeUInt32LE(0x04034b50, 0);
  local.writeUInt16LE(20, 4);
  local.writeUInt16LE(flags, 6);
  local.writeUInt16LE(method, 8);
  if (!options.descriptor || options.localSizes) {
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(packed.length, 18);
    local.writeUInt32LE(size, 22);
  }
  local.writeUInt16LE(nameBytes.length, 26);
  let descriptor = Buffer.alloc(0);
  if (options.descriptor) {
    const start = options.signature === false ? 0 : 4;
    descriptor = Buffer.alloc(start + 12);
    if (start) descriptor.writeUInt32LE(0x08074b50, 0);
    descriptor.writeUInt32LE(crc, start);
    descriptor.writeUInt32LE(packed.length, start + 4);
    descriptor.writeUInt32LE(size, start + 8);
  }
  central.writeUInt32LE(0x02014b50, 0);
  central.writeUInt16LE(0x0314, 4);
  central.writeUInt16LE(20, 6);
  central.writeUInt16LE(flags, 8);
  central.writeUInt16LE(method, 10);
  central.writeUInt32LE(crc, 16);
  central.writeUInt32LE(packed.length, 20);
  central.writeUInt32LE(size, 24);
  central.writeUInt16LE(nameBytes.length, 28);
  central.writeUInt32LE(options.attrs ?? 0, 38);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(1, 8);
  end.writeUInt16LE(1, 10);
  end.writeUInt32LE(46 + nameBytes.length, 12);
  end.writeUInt32LE(30 + nameBytes.length + packed.length + descriptor.length, 16);
  return Buffer.concat([local, nameBytes, packed, descriptor, central, nameBytes, end]);
}
function combine(archives) {
  const locals = [], centrals = [];
  let offset = 0, centralSize = 0;
  for (const archive of archives) {
    const split = centralOffset(archive);
    locals.push(archive.subarray(0, split));
    const record = Buffer.from(archive.subarray(split, endOffset(archive)));
    record.writeUInt32LE(offset, 42);
    centrals.push(record);
    offset += split;
    centralSize += record.length;
  }
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(archives.length, 8);
  end.writeUInt16LE(archives.length, 10);
  end.writeUInt32LE(centralSize, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, ...centrals, end]);
}
function withExtra(archive, extra, where) {
  const split = where === "central" ? endOffset(archive) : 30 + archive.readUInt16LE(26);
  const output = Buffer.concat([archive.subarray(0, split), extra, archive.subarray(split)]);
  if (where === "central") {
    output.writeUInt16LE(extra.length, centralOffset(archive) + 30);
    output.writeUInt32LE(archive.readUInt32LE(endOffset(archive) + 12) + extra.length, endOffset(output) + 12);
  } else {
    output.writeUInt16LE(extra.length, 28);
    output.writeUInt32LE(centralOffset(archive) + extra.length, endOffset(output) + 16);
  }
  return output;
}

test("office ZIP: stored roundtrip preserves Unicode names, binary data, and empty files", () => {
  const files = [
    { name: "skills/ทีม/SKILL.md", data: Buffer.from("# ทักษะ\n") },
    { name: "assets/binary.bin", data: Buffer.from([0, 1, 127, 128, 254, 255]) },
    { name: "workflows/empty.md", data: Buffer.alloc(0) },
    { name: "\ufeffname.md", data: Buffer.from("BOM belongs to this filename") },
  ];
  assert.deepEqual(zip.decode(zip.encode(files)), files);
  assert.deepEqual(zip.decode(zip.encode([])), []);
  assert.deepEqual(zip.decode(zip.encode([{ name: "text.md", data: "hello" }])), [{ name: "text.md", data: Buffer.from("hello") }]);
  const standardCrc = zip.encode([{ name: "crc.txt", data: "123456789" }]);
  assert.equal(standardCrc.readUInt32LE(14), 0xcbf43926);
});

test("office ZIP: reads Python zipfile deflate output, directories, Unicode, and archive comments", () => {
  // Generated by Python's standard-library ZipFile, ZIP_DEFLATED.
  const archive = Buffer.from("UEsDBBQAAAAIAGcqOl0AAAAAAgAAAAAAAAAHAAAAc2tpbGxzLwMAUEsDBBQAAAgIAGcqOl0aSV7uEwAAABEAAAAZAAAAc2tpbGxzL+C4l+C4teC4oS9TS0lMTC5tZFNWCMgvKklMyklVKM7OzMnhAgBQSwMEFAAAAAgAZyo6Xe3CBzYGAAAABAAAAAoAAABiaW5hcnkuZGF0Y2Bs+A8AUEsBAhQAFAAAAAgAZyo6XQAAAAACAAAAAAAAAAcAAAAAAAAAAAAQAP1BAAAAAHNraWxscy9QSwECFAAUAAAICABnKjpdGkle7hMAAAARAAAAGQAAAAAAAAAAAAAAgAEnAAAAc2tpbGxzL+C4l+C4teC4oS9TS0lMTC5tZFBLAQIUABQAAAAIAGcqOl3twgc2BgAAAAQAAAAKAAAAAAAAAAAAAACAAXEAAABiaW5hcnkuZGF0UEsFBgAAAAADAAMAtAAAAJ8AAAAYAG9yZGluYXJ5IGFyY2hpdmUgY29tbWVudA==", "base64");
  assert.deepEqual(zip.decode(archive), [
    { name: "skills/ทีม/SKILL.md", data: Buffer.from("# Portable skill\n") },
    { name: "binary.dat", data: Buffer.from([0, 1, 128, 255]) },
  ]);
  assert.deepEqual(zip.decode(zip.encode([{ name: "empty/", data: "" }])), []);
});

test("office ZIP: supports legacy CP437 names and signed/unsigned stream descriptors", () => {
  assert.equal(zip.decode(fixture(Buffer.from([0x82, 0x2e, 0x6d, 0x64]), Buffer.from("ok"), { flags: 0 }))[0].name, "é.md");
  for (const method of [0, 8]) for (const signature of [true, false]) for (const localSizes of [true, false]) {
    const data = Buffer.from("streamed bytes\n".repeat(100));
    assert.deepEqual(zip.decode(fixture("stream.md", data, { method, descriptor: true, signature, localSizes })), [{ name: "stream.md", data }]);
  }
});

test("office ZIP: rejects unsafe portable paths on export and import", () => {
  const names = ["../escape", "a/../../escape", "/absolute", "C:/absolute", "C:relative", "//server/share", "\\server\\share", "a\\..\\escape", "a//b", "./a", "a/./b", "a/../b", "a\0b", "a\nb", "foo:ads", "dir/CON.txt", "NUL", "a/COM1.md", "LPT9", "COM¹.log", "CONIN$", "CONOUT$.log", "con .txt", "a.", "a ", "a/b. /c", "a?b", "a*b", 'a"b', "a<b", "a|b"];
  for (const name of names) {
    assert.throws(() => zip.encode([{ name, data: "x" }]), /entry path/, name);
    assert.throws(() => zip.decode(fixture(name)), /entry path/, name);
  }
  assert.throws(() => zip.decode(fixture("")), /entry path/);
  assert.throws(() => zip.encode([{ name: "bad\ud800.md", data: "x" }]), /filename/);
  assert.throws(() => zip.decode(fixture(Buffer.from([0xff]))), /UTF-8/);
});

test("office ZIP: prevents case/Unicode duplicates and file-directory collisions", () => {
  for (const names of [["a.md", "A.md"], ["é.md", "e\u0301.md"], ["a", "a/"], ["dir/file.md", "DIR"], ["a", "a/b"]]) {
    assert.throws(() => zip.encode(names.map((name) => ({ name, data: "" }))), /duplicate|parent directory/);
    assert.throws(() => zip.decode(combine(names.map((name) => fixture(name, Buffer.alloc(0))))), /duplicate|parent directory/);
  }
  assert.equal(zip.decode(combine([fixture("dir/", Buffer.alloc(0)), fixture("dir/a", Buffer.from("x"))])).length, 1);
});

test("office ZIP: rejects symlinks, devices, and inconsistent directory attributes", () => {
  for (const attrs of [0xa1ff0000, 0x21ff0000, 0x61ff0000, 0x11ff0000, 8, 0x10, 0x41ed0000]) {
    assert.throws(() => zip.decode(fixture("file", Buffer.from("x"), { attrs })), /nonregular|directory attributes/);
  }
  assert.throws(() => zip.decode(fixture("dir/", Buffer.alloc(0), { attrs: 0x81a40000 })), /file attributes/);
  assert.throws(() => zip.decode(fixture("dir/", Buffer.from("x"))), /directory entry has data/);
  assert.throws(() => zip.encode([{ name: "dir/", data: "x" }]), /directory entry has data/);
});

test("office ZIP: validates local/central filenames, flags, methods, sizes, and CRC", () => {
  for (const [offset, value] of [[4, 10], [6, 0], [8, 8], [14, 0], [18, 0], [22, 0]]) {
    const archive = zip.encode([{ name: "file.md", data: "data" }]);
    if (offset < 14) archive.writeUInt16LE(value, offset); else archive.writeUInt32LE(value, offset);
    assert.throws(() => zip.decode(archive), /metadata mismatch|size or checksum mismatch/);
  }
  const badName = zip.encode([{ name: "file.md", data: "data" }]);
  badName[30] = 0x78;
  assert.throws(() => zip.decode(badName), /filename mismatch/);
  const badPayload = zip.encode([{ name: "file.md", data: "data" }]);
  badPayload[37] ^= 1;
  assert.throws(() => zip.decode(badPayload), /checksum mismatch/);
  const badDescriptor = fixture("file.md", Buffer.from("data"), { descriptor: true });
  badDescriptor[centralOffset(badDescriptor) - 1] ^= 1;
  assert.throws(() => zip.decode(badDescriptor), /data descriptor/);
});

test("office ZIP: rejects unsupported flags, compression, ZIP64 and multidisk records", () => {
  for (const flag of [1, 0x10, 0x20, 0x40, 0x2000, 0x4000]) assert.throws(() => zip.decode(fixture("a", Buffer.from("x"), { flags: 0x800 | flag })), /flags/);
  assert.throws(() => zip.decode(fixture("a", Buffer.from("x"), { method: 99 })), /compression/);
  assert.throws(() => zip.decode(fixture("a", Buffer.from("x"), { method: 0, flags: 0x802 })), /flags/);
  for (const [target, field, value, width] of [["end", 4, 1, 2], ["end", 6, 1, 2], ["end", 8, 2, 2], ["end", 10, 0xffff, 2], ["end", 12, 0xffffffff, 4], ["central", 6, 45, 2], ["central", 20, 0xffffffff, 4], ["central", 34, 1, 2], ["central", 42, 0xffffffff, 4]]) {
    const archive = fixture("a");
    const offset = target === "end" ? endOffset(archive) : centralOffset(archive);
    if (width === 2) archive.writeUInt16LE(value, offset + field); else archive.writeUInt32LE(value, offset + field);
    assert.throws(() => zip.decode(archive), /ZIP64|multidisk/);
  }
});

test("office ZIP: validates local and central extra fields without accepting ZIP64", () => {
  for (const where of ["local", "central"]) {
    assert.throws(() => zip.decode(withExtra(fixture("a"), Buffer.from([1, 0, 0, 0]), where)), /ZIP64/);
    assert.throws(() => zip.decode(withExtra(fixture("a"), Buffer.from([0xfe, 0xca, 1, 0]), where)), /bounds/);
    assert.throws(() => zip.decode(withExtra(fixture("a"), Buffer.from([0xfe, 0xca, 0]), where)), /bounds/);
    assert.equal(zip.decode(withExtra(fixture("a"), Buffer.from([0xfe, 0xca, 0, 0]), where))[0].data.toString(), "payload");
  }
});

test("office ZIP: rejects truncated records, offsets, hidden data, and overlapping local entries", () => {
  const archive = fixture("file.md");
  for (const cut of [0, 1, 5, 21, archive.length - 1]) assert.throws(() => zip.decode(archive.subarray(0, cut)), /ZIP/);
  const offset = Buffer.from(archive);
  offset.writeUInt32LE(0xfffffff0, centralOffset(offset) + 42);
  assert.throws(() => zip.decode(offset), /bounds/);
  const hugeName = Buffer.from(archive);
  hugeName.writeUInt16LE(0xffff, centralOffset(hugeName) + 28);
  assert.throws(() => zip.decode(hugeName), /bounds/);
  const hugeCentral = Buffer.from(archive);
  hugeCentral.writeUInt32LE(0x7fffffff, endOffset(hugeCentral) + 12);
  assert.throws(() => zip.decode(hugeCentral), /bounds/);
  const withPrefix = Buffer.concat([Buffer.from("extra"), archive]);
  withPrefix.writeUInt32LE(centralOffset(archive) + 5, endOffset(withPrefix) + 16);
  withPrefix.writeUInt32LE(5, centralOffset(withPrefix) + 42);
  assert.throws(() => zip.decode(withPrefix), /unexpected data/);
  // Two central records alias one local record with different Unicode spellings.
  const overlap = combine([fixture("a"), fixture("b")]);
  overlap.writeUInt32LE(0, centralOffset(overlap) + 47 + 42);
  assert.throws(() => zip.decode(overlap), /filename mismatch|overlapping/);
});

test("office ZIP: bounds archive, entry count, uncompressed sizes, and deflate expansion", () => {
  assert.throws(() => zip.decode(Buffer.alloc(zip.MAX_ARCHIVE_BYTES + 1)), /archive exceeds/);
  assert.throws(() => zip.encode([{ name: "a", data: Buffer.alloc(zip.MAX_ENTRY_BYTES + 1) }]), /entry exceeds/);
  assert.throws(() => zip.encode(Array.from({ length: zip.MAX_ENTRIES + 1 }, (_, n) => ({ name: String(n), data: "" }))), /too many/);
  const count = fixture("a");
  count.writeUInt16LE(zip.MAX_ENTRIES + 1, endOffset(count) + 8);
  count.writeUInt16LE(zip.MAX_ENTRIES + 1, endOffset(count) + 10);
  assert.throws(() => zip.decode(count), /too many/);
  const data = Buffer.alloc(zip.MAX_ENTRY_BYTES, 65);
  assert.throws(() => zip.encode(Array.from({ length: 3 }, (_, n) => ({ name: String(n), data }))), /archive exceeds/);
  assert.throws(() => zip.encode(Array.from({ length: 9 }, (_, n) => ({ name: String(n), data }))), /total uncompressed/);
  assert.equal(zip.decode(fixture("at-limit", data))[0].data.length, zip.MAX_ENTRY_BYTES);
  assert.throws(() => zip.decode(fixture("large", Buffer.from("x"), { size: zip.MAX_ENTRY_BYTES + 1 })), /entry exceeds/);
  const tiny = fixture("bomb", data, { size: 1 });
  assert.ok(tiny.length < 10000);
  assert.throws(() => zip.decode(tiny), /oversized deflate/);
  // Declared aggregate size is rejected before any payload is inflated.
  const tooManyBytes = combine(Array.from({ length: 9 }, (_, n) => fixture(String(n), Buffer.from("x"), { size: zip.MAX_ENTRY_BYTES })));
  assert.throws(() => zip.decode(tooManyBytes), /total uncompressed/);
  assert.throws(() => zip.decode(fixture("bad", Buffer.from("x"), { packed: Buffer.from([0xff, 0xff]) })), /deflate/);
  assert.throws(() => zip.decode(fixture("tail", Buffer.from("x"), { packed: Buffer.concat([deflateRawSync(Buffer.from("x")), Buffer.from("extra")]) })), /trailing compressed/);
  assert.throws(() => zip.decode(fixture("short", Buffer.from("x"), { size: 2 })), /uncompressed size mismatch/);
});
